### ISSUE TITLE
Fix the documentation of the config files

### ISSUE THREAD

**Issue by pronobis** [pronobis/rocs#15]
Update the documentation of the config files on the wiki. Port it to the Doxygen and formulate as a users manual. The Doxygen documentation should be used as a user's manual while the Wiki as a help for ROCS developers.

Other things to change at the same time:
- Add examples for every case in all possible configuration format. Currently, the documentation is quite fragmented mostly focuses on XML.

Assigned: arnaud

**Comment by pronobis** [comment]
Also, is the last example correct? I don't really understand the sentence " The first item, that doesn’t contain any foo field, won’t trigger an error."

**Comment by arnaud-ramey** [comment]
the last sentence contained a mistake : it was a "item" field. Doc updated.
