### ISSUE TITLE
Add includes in the command line

### ISSUE THREAD

**Issue by pronobis** [pronobis/rocs#19]
Add the ability to include config files from the command line. This should work in a similar way as for other configuration file formats. In XML, there is an include keyword. We should have an include keyword for each configuration file AND the command line. This way we can add config files from the command line.

Assigned: arnaud

**Comment by arnaud-ramey** [comment]
added a test for INFO files.
The include tags have been defined (it is more or less 'include href="filename"'), the details are in the doxygen doc of the Configuration class
